# Code-along 2024-07-02 Machine Learning in Production with Python  by Michelle Conway

### Summary for Code-Along Session

**Background Context:**

In this code-along session, we will work with a dataset from a Portuguese banking institution's direct marketing campaigns, sourced from Kaggle. The dataset contains information about various marketing efforts, including telephonic outreach, aimed at promoting term deposits. Term deposits are significant for banks as they provide a stable income stream. Identifying and targeting potential customers effectively can enhance marketing efficiency and reduce costs.

https://www.kaggle.com/datasets/prakharrathi25/banking-dataset-marketing-targets/data

https://github.com/mconwa02/datacamp-code-along-2024

**Tasks Covered:**

1. **Feature Engineering**:
   - We will develope functions to enhance the DataFrame with new features.
   - These functions were combined into a streamlined data transformation process using the Pandas `pipe` method.

2. **Unit Testing**:
   - We implemented unit tests using the `pytest` framework to ensure the new features were correctly added to the DataFrame.
   - The tests verified that the new columns were accurately calculated and correctly incorporated into the DataFrame.

Overall, this session provided practical experience in enhancing a dataset with valuable features and ensuring the robustness of these enhancements through thorough testing.

### Loading Data
This code processes a dataset containing bank client data from a CSV file, performing several transformations and aggregations. It reads the CSV file into a DataFrame and then prints detailed information about the structure and contents of that DataFrame.

In [1]:
# Loading Data: Reads the data from a CSV file into a Pandas DataFrame.
import pandas as pd

df = pd.read_csv("train.csv", sep=';')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

### Adding New Columns
### annual_duration 
Adds a column with a nested list for each value in the duration column, where each entry is a list containing the value and its half.

In [2]:
df['annual_duration'] = [[i, i/2] for i in df['duration']]
df['annual_duration'].head()

0    [261, 130.5]
1     [151, 75.5]
2      [76, 38.0]
3      [92, 46.0]
4     [198, 99.0]
Name: annual_duration, dtype: object

### campaign_limit 
Adds a column with a tuple for each value in the campaign column, where each entry is a tuple containing the value and its square.

In [3]:
df['campaign_limit'] = [(i, i ** 2) for i in df['campaign']]
df['campaign_limit'].head()

0    (1, 1)
1    (1, 1)
2    (1, 1)
3    (1, 1)
4    (1, 1)
Name: campaign_limit, dtype: object

### Grouping and Aggregating

- Groups the DataFrame by the marital column.
- Applies a lambda function to aggregate the grouped data into a new DataFrame with the following columns:
    - balance_max: Maximum value of the balance column within each group.
    - age_mean: Mean value of the age column within each group.
    - annual_duration_flat: Flattened list of all annual_duration values within each group.
    - campaign_limit_concat: Concatenated string of all campaign_limit values within each group.

In [4]:
result = df.groupby('marital').apply(
    lambda x: pd.Series(
        {
            'balance_max': x['balance'].max(),
            'age_mean': x['age'].mean()
        }
    )
)

### Printing the Result
Outputs the columns of aggregated result DataFrame and prints the values in the balance_max and age_mean columns.

In [5]:
print(result)

          balance_max   age_mean
marital
divorced      66721.0  45.782984
married       98417.0  43.408099
single       102127.0  33.703440

### Function Definitions
This code enhances a DataFrame containing banking customer data by adding new features derived from existing columns using fucntions.

The max_customer_account_balance function below takes a DataFrame as input and adds a new column, balance_max, which contains the maximum account balance from the balance column across all customers.

In [6]:
import pandas as pd
from pandas import DataFrame

def max_customer_account_balance(df: DataFrame) -> DataFrame:
    """Add a column with the mean age of all customer"""
    df['balance_max'] = df['balance'].max()
    return df

max_customer_account_balance(df)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,annual_duration,campaign_limit,balance_max
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no,"[261, 130.5]","(1, 1)",102127
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no,"[151, 75.5]","(1, 1)",102127
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,"[76, 38.0]","(1, 1)",102127
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no,"[92, 46.0]","(1, 1)",102127
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no,"[198, 99.0]","(1, 1)",102127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes,"[977, 488.5]","(3, 9)",102127
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes,"[456, 228.0]","(2, 4)",102127
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes,"[1127, 563.5]","(5, 25)",102127
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no,"[508, 254.0]","(4, 16)",102127
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no,"[361, 180.5]","(2, 4)",102127

The customers_mean_age function below takes a DataFrame as input and adds a new column, age_mean, which contains the mean age of all customers from the age column.

In [7]:
def customers_mean_age(df: DataFrame) -> DataFrame:
    """Add a column with the mean age of all customer"""
    df['age_mean'] = df['age'].mean()
    return df

customers_mean_age(df)

,age,job,marital,education,default,balance,housing,loan,contact,day,...,duration,campaign,pdays,previous,poutcome,y,annual_duration,campaign_limit,balance_max,age_mean
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,...,261,1,-1,0,unknown,no,"[261, 130.5]","(1, 1)",102127,40.93621
1,44,technician,single,secondary,no,29,yes,no,unknown,5,...,151,1,-1,0,unknown,no,"[151, 75.5]","(1, 1)",102127,40.93621
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,...,76,1,-1,0,unknown,no,"[76, 38.0]","(1, 1)",102127,40.93621
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,...,92,1,-1,0,unknown,no,"[92, 46.0]","(1, 1)",102127,40.93621
4,33,unknown,single,unknown,no,1,no,no,unknown,5,...,198,1,-1,0,unknown,no,"[198, 99.0]","(1, 1)",102127,40.93621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,...,977,3,-1,0,unknown,yes,"[977, 488.5]","(3, 9)",102127,40.93621
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,...,456,2,-1,0,unknown,yes,"[456, 228.0]","(2, 4)",102127,40.93621
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,...,1127,5,184,3,success,yes,"[1127, 563.5]","(5, 25)",102127,40.93621
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,...,508,4,-1,0,unknown,no,"[508, 254.0]","(4, 16)",102127,40.93621
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,...,361,2,188,11,other,no,"[361, 180.5]","(2, 4)",102127,40.93621

In [9]:
def gb_customer_mean_age(df: DataFrame) -> DataFrame:
    """Add a column with the mean age of all customer"""
    df['age_mean'] = df['age'].mean()
    return df['age_mean'].iloc[0]

In [10]:
def gb_max_customer_account_age(df: DataFrame) -> DataFrame:
    """Add a column with the mean age of all customer"""
    df['balance_max'] = df['balance'].mean()
    return df['balance_max'].iloc[0]

In [11]:
df.groupby('marital').apply(
    lambda x: pd.Series(
        {
            'balance_max': x['balance'].max(),
            'age_mean': gb_max_customer_account_age(x),
        }
    )
)

          balance_max     age_mean
marital
divorced      66721.0  1178.872287
married       98417.0  1425.925590
single       102127.0  1301.497654

In [13]:
df.groupby('marital').apply(
    lambda x: pd.Series(
        {
            'balance_max': customers_mean_age(x),
            'age_mean': max_customer_account_balance(x),
        }
    )
)

,balance_max,age_mean
marital,,
divorced,age job marital education ...,age job marital education ...
married,age job marital education d...,age job marital education d...
single,age job marital education def...,age job marital education def...

### Feature Creation Pipeline

This creating_features_banking_data function applies the max_customer_account_balance and customers_mean_age functions to the DataFrame using the Pandas pipe method. This method allows for a clean and readable chaining of operations.
It returns the modified DataFrame with the new features added

In [ ]:
df = max_customer_account_balance(df)
df = customers_mean_age(df)
df = sum_balanced_and_age(df)

In [ ]:
df.pipe(max_customer_account_balance).pipe(customers_mean_age).pipe(sum_balanced_and_age)

,age,job,marital,education,default,balance,housing,loan,contact,day,...,duration,campaign,pdays,previous,poutcome,y,annual_duration,campaign_limit,balance_max,age_mean
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,...,261,1,-1,0,unknown,no,"[261, 130.5]","(1, 1)",102127,40.93621
1,44,technician,single,secondary,no,29,yes,no,unknown,5,...,151,1,-1,0,unknown,no,"[151, 75.5]","(1, 1)",102127,40.93621
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,...,76,1,-1,0,unknown,no,"[76, 38.0]","(1, 1)",102127,40.93621
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,...,92,1,-1,0,unknown,no,"[92, 46.0]","(1, 1)",102127,40.93621
4,33,unknown,single,unknown,no,1,no,no,unknown,5,...,198,1,-1,0,unknown,no,"[198, 99.0]","(1, 1)",102127,40.93621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,...,977,3,-1,0,unknown,yes,"[977, 488.5]","(3, 9)",102127,40.93621
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,...,456,2,-1,0,unknown,yes,"[456, 228.0]","(2, 4)",102127,40.93621
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,...,1127,5,184,3,success,yes,"[1127, 563.5]","(5, 25)",102127,40.93621
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,...,508,4,-1,0,unknown,no,"[508, 254.0]","(4, 16)",102127,40.93621
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,...,361,2,188,11,other,no,"[361, 180.5]","(2, 4)",102127,40.93621

### Execution

Calls the creating_features_banking_data function with the sample DataFrame df.
Stores the resulting DataFrame in banking_customers_df.
Prints the first few rows of the resulting DataFrame to verify the added features.

In [14]:
import pytest

@pytest.fixture()
def test_df():
    return DataFrame(
        data={
            "balance": [100, 200, 300, 400, 500],
            "age": [30, 40, 50, 60, 70]
        }
    )

ModuleNotFoundError: No module named 'pytest'

### Unit Testing

This code provides unit tests for two functions, `max_customer_account_balance` and `customers_mean_age`, using the `pytest` framework. The goal is to ensure that these functions correctly add calculated columns to a Pandas DataFrame.

**Imports and Fixtures**:
   - Imports the necessary modules and functions: `pytest`, `DataFrame` from Pandas, and the productions functions.
   - Defines a fixture `test_df` that sets up a sample DataFrame for testing purposes.

**Unit Test for `max_customer_account_balance` Function**
   - Creates a DataFrame with balance data.
   - Applies the `max_customer_account_balance` function to add the `balance_max` column.
   - Asserts that the `balance_max` column is present and contains the correct maximum value (500).

In [17]:
def test_max_customer_account_balance():
    test_df = DataFrame(data={"balance": [100, 200, 300, 400, 500]})
    actual_df = max_customer_account_balance(test_df)
    actual = actual_df['balance_max'].iloc[0]
    expect = 500
    assert "balance_max" in test_df.columns
    assert actual == expect

In [18]:
test_max_customer_account_balance()

In [20]:
def test_customer_mean_age():
    test_df = DataFrame(data={"age": [30, 40, 50, 60, 70]})
    actual_df = max_customer_account_balance(test_df)
    actual = actual_df['age_mean'].iloc[0]
    expect = 50
    assert "age_mean" in test_df.columns
    assert actual == expect

**Unit Test for `customers_mean_age` Function**:
   - Creates a DataFrame with age data.
   - Applies the `customers_mean_age` function to add the `age_mean` column.
   - Asserts that the `age_mean` column is present and contains the correct mean value (50).

In [1]:
def

**Purpose**:
- Ensure the `max_customer_account_balance` function correctly computes and adds the maximum account balance as a new column.
- Ensure the `customers_mean_age` function correctly computes and adds the mean age of customers as a new column.

These tests validate the correctness of the feature engineering functions, ensuring they perform as expected when applied to a DataFrame.